
"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const fmt=(n,d=2)=>new Intl.NumberFormat('pl-PL',{maximumFractionDigits:d}).format(Number.isFinite(n)?n:0);
const money=n=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:2}).format(Number.isFinite(n)?n:0);
const val=(obj,id)=>Number(String(obj[id]??0).replace(',','.'))||0;
const pct=v=>1+v/100;
const row=(label,value)=>({label,value});
const res=(label,value,rows=[],warning='',shopping=[])=>({label,value,rows,warning,shopping});
const field=(id,label,unit,value,advanced=false,hint='')=>({id,label,unit,value,type:'number',advanced,hint});
const select=(id,label,options,value,advanced=false)=>({id,label,options,value:value||options[0][0],type:'select',advanced});
const cats=[
 {id:'budowa',name:'Budowa i remont',icon:'🏗️',tint:'#fff0ec',desc:'Beton, płytki, fuga, dylatacje, powierzchnie, spadki i straty materiału.'},
 {id:'dach',name:'Dach i poddasze',icon:'🏠',tint:'#edf4ff',desc:'Krokwie, kąt dachu, rozstaw łat, izolacja poddasza i powierzchnie połaci.'},
 {id:'drewno',name:'Drewno i tarasy',icon:'🪵',tint:'#fff6df',desc:'Deski tarasowe, legary, wkręty i podstawy konstrukcji drewnianych.'},
 {id:'instalacje',name:'Instalacje',icon:'⚙️',tint:'#eaf9fb',desc:'Spadek kanalizacji, wentylacja pomieszczeń i podstawowe przeliczenia.'},
 {id:'koszty',name:'Koszty i zlecenia',icon:'📊',tint:'#ebfaf3',desc:'Robocizna, wynajem narzędzi, koszt materiałów i porównanie wariantów.'}
];
const calcs=[
 {id:'schody',cat:'budowa',icon:'🪜',name:'Kalkulator schodów',tag:'ergonomia',desc:'Liczba stopni, rzeczywista wysokość i długość biegu.',formula:'n = wysokość / wysokość stopnia; 2h + s = 60–65 cm',fields:[field('height','Wysokość do pokonania','cm',280),field('targetH','Docelowa wysokość stopnia','cm',17.5),field('tread','Głębokość stopnia','cm',28),field('price','Cena wykonania za stopień','zł',0,true)],guide:'Wygodne schody najczęściej mieszczą się w regule 2h + s = 60–65 cm.',example:'Dla 280 cm i stopnia ok. 17,5 cm wychodzi około 16 stopni.',mistakes:'Nie ignoruj grubości posadzki, okładziny stopnia i wykończenia spocznika.',calc:d=>{let n=Math.round(val(d,'height')/val(d,'targetH'));let h=val(d,'height')/n;let run=n*val(d,'tread')/100;let comfort=2*h+val(d,'tread');let cost=n*val(d,'price');return res('Liczba stopni',`${n} szt.`,[row('Rzeczywista wysokość',`${fmt(h,1)} cm`),row('Długość biegu',`${fmt(run,2)} m`),row('Wzór wygody 2h+s',`${fmt(comfort,1)} cm`),row('Koszt orientacyjny',val(d,'price')?money(cost):'nie podano')],comfort<60||comfort>65?'Wynik poza typowym zakresem komfortu 60–65 cm.':'Zakres komfortu wygląda poprawnie orientacyjnie.',[`Schody: ${n} stopni`, `Bieg ok. ${fmt(run,2)} m`]);}},
 {id:'spadek-kanalizacji',cat:'instalacje',icon:'↘️',name:'Kalkulator spadku kanalizacji',tag:'instalacje',desc:'Różnica wysokości rury dla zadanego spadku.',formula:'h = długość × spadek [cm/m]',fields:[field('length','Długość odcinka','m',6),field('slope','Spadek','cm/m',2),field('cost','Cena rury za metr','zł/m',0,true)],guide:'Dla kanalizacji wewnętrznej często stosuje się spadki rzędu 2–3 cm/m, ale dobór zależy od średnicy i układu.',example:'6 m przy 2 cm/m daje 12 cm różnicy wysokości.',mistakes:'Za mały spadek sprzyja zastojom, za duży może powodować odpływ wody bez transportu części stałych.',calc:d=>{let h=val(d,'length')*val(d,'slope'),cost=val(d,'length')*val(d,'cost');return res('Różnica wysokości',`${fmt(h,1)} cm`,[row('Spadek w %',`${fmt(val(d,'slope'))}%`),row('Długość odcinka',`${fmt(val(d,'length'),2)} m`),row('Koszt rury',val(d,'cost')?money(cost):'nie podano')],val(d,'slope')<1.5||val(d,'slope')>3.5?'Sprawdź zalecenia dla konkretnej średnicy rury i układu instalacji.':'Spadek wygląda typowo orientacyjnie.',[`Rura kanalizacyjna: ${fmt(val(d,'length'),2)} m`]);}},
 {id:'spadek-tarasu',cat:'budowa',icon:'📐',name:'Kalkulator spadku tarasu',tag:'spadki',desc:'Spadek tarasu, posadzki lub chodnika w % i cm.',formula:'różnica = długość × spadek / 100',fields:[field('length','Długość spadku','m',4),field('slope','Spadek','%',2),field('width','Szerokość tarasu','m',3,true),field('price','Koszt wykonania za m²','zł/m²',0,true)],guide:'Tarasy zwykle projektuje się ze spadkiem od budynku, aby woda nie stała przy ścianie.',example:'4 m przy 2% daje 8 cm różnicy wysokości.',mistakes:'Najczęstszy błąd to spadek w stronę budynku lub brak ciągłości hydroizolacji.',calc:d=>{let drop=val(d,'length')*val(d,'slope'),area=val(d,'length')*val(d,'width'),cost=area*val(d,'price');return res('Różnica wysokości',`${fmt(drop,1)} cm`,[row('Długość',`${fmt(val(d,'length'),2)} m`),row('Powierzchnia',val(d,'width')?`${fmt(area,2)} m²`:'nie podano'),row('Koszt orientacyjny',val(d,'price')?money(cost):'nie podano')],'Sprawdź warstwy tarasu: spadek, izolację, odwodnienie i wysokość przy progu.',[`Powierzchnia tarasu: ${fmt(area,2)} m²`]);}},
 {id:'dlugosc-krokwi',cat:'dach',icon:'📏',name:'Kalkulator długości krokwi',tag:'dach',desc:'Długość krokwi z rozpiętości, kąta i okapu.',formula:'krokiew = (rozpiętość/2 + okap) / cos(kąt)',fields:[field('span','Szerokość budynku','m',6),field('angle','Kąt dachu','°',35),field('eave','Okap poziomy','m',0.5),field('waste','Zapas na docięcie','cm',10,true),field('price','Cena drewna za mb','zł/mb',0,true)],guide:'Kalkulator podaje długość geometryczną. Zaciosy, murłata i detal kalenicy wymagają projektu.',example:'Budynek 6 m, dach 35° i okap 0,5 m daje krokiew ok. 4,27 m.',mistakes:'Nie myl długości połaci z rzutem poziomym. Długość krokwi rośnie wraz z kątem dachu.',calc:d=>{let a=val(d,'angle')*Math.PI/180;let l=(val(d,'span')/2+val(d,'eave'))/Math.cos(a)+val(d,'waste')/100;let rise=(val(d,'span')/2)*Math.tan(a);let cost=l*val(d,'price');return res('Długość krokwi',`${fmt(l,2)} m`,[row('Wysokość kalenicy od murłaty',`${fmt(rise,2)} m`),row('Kąt dachu',`${fmt(val(d,'angle'),1)}°`),row('Koszt jednej krokwi',val(d,'price')?money(cost):'nie podano')],'To wynik geometryczny, nie zastępuje projektu więźby.',[`Krokiew: ${fmt(l,2)} m`]);}},
 {id:'kat-dachu',cat:'dach',icon:'△',name:'Kalkulator kąta dachu',tag:'dach',desc:'Kąt dachu z wysokości i połowy rozpiętości.',formula:'kąt = arctan(wysokość / połowa rozpiętości)',fields:[field('rise','Wysokość od murłaty do kalenicy','m',2.1),field('half','Połowa rozpiętości','m',3),field('roofL','Długość budynku','m',8,true),field('waste','Zapas pokrycia','%',10,true)],guide:'Kąt dachu jest kluczowy dla doboru pokrycia, obróbek i sposobu wentylacji połaci.',example:'2,1 m wysokości i 3 m połowy rozpiętości daje około 35°.',mistakes:'Nie pomijaj minimalnego kąta dopuszczonego przez producenta pokrycia.',calc:d=>{let angle=Math.atan(val(d,'rise')/val(d,'half'))*180/Math.PI;let rafter=Math.sqrt(val(d,'rise')**2+val(d,'half')**2);let area=val(d,'roofL')?rafter*val(d,'roofL')*2*pct(val(d,'waste')):0;return res('Kąt dachu',`${fmt(angle,1)}°`,[row('Spadek',`${fmt(val(d,'rise')/val(d,'half')*100,1)}%`),row('Długość krokwi bez okapu',`${fmt(rafter,2)} m`),row('Powierzchnia połaci z zapasem',area?`${fmt(area,1)} m²`:'nie podano')],'Dobór pokrycia sprawdź w karcie technicznej producenta.',[`Kąt dachu: ${fmt(angle,1)}°`]);}},
 {id:'rozstaw-lat',cat:'dach',icon:'▤',name:'Kalkulator rozstawu łat',tag:'dach',desc:'Liczba łat na połaci według rozstawu.',formula:'liczba łat = długość połaci / rozstaw + 1',fields:[field('rafter','Długość połaci','m',5),field('spacing','Rozstaw łat','cm',35),field('roofL','Długość dachu','m',8),field('price','Cena łaty za mb','zł/mb',0,true)],guide:'Rozstaw łat musi odpowiadać konkretnemu pokryciu, np. dachówce lub blasze modułowej.',example:'Połać 5 m i rozstaw 35 cm wymaga ok. 16 rzędów łat.',mistakes:'Nie ustawiaj rozstawu „na oko”. Zawsze sprawdź wymiar krycia pokrycia.',calc:d=>{let rows=Math.ceil(val(d,'rafter')/(val(d,'spacing')/100))+1;let mb=rows*val(d,'roofL');let cost=mb*val(d,'price');return res('Liczba rzędów łat',`${rows} szt.`,[row('Łaty łącznie',`${fmt(mb,1)} mb`),row('Rozstaw',`${fmt(val(d,'spacing'),1)} cm`),row('Koszt orientacyjny',val(d,'price')?money(cost):'nie podano')],'Sprawdź rozstaw z instrukcją montażu wybranego pokrycia.',[`Łaty: ${fmt(mb,1)} mb`]);}},
 {id:'wkretow',cat:'drewno',icon:'🔩',name:'Kalkulator ilości wkrętów',tag:'montaż',desc:'Ile wkrętów potrzeba do desek, płyt lub elementów.',formula:'wkręty = elementy × punkty mocowania × wkręty na punkt × zapas',fields:[field('elements','Liczba elementów','szt.',40),field('points','Punkty mocowania na element','szt.',4),field('screws','Wkręty na punkt','szt.',2),field('waste','Zapas','%',10),field('box','Wkrętów w opakowaniu','szt.',200,true),field('price','Cena opakowania','zł',0,true)],guide:'Do tarasów często stosuje się po 2 wkręty na każde przecięcie deski z legarem.',example:'40 desek × 4 punkty × 2 wkręty = 320 szt. przed zapasem.',mistakes:'Zbyt mała liczba wkrętów powoduje pracę elementu i skrzypienie.',calc:d=>{let total=Math.ceil(val(d,'elements')*val(d,'points')*val(d,'screws')*pct(val(d,'waste')));let packs=Math.ceil(total/val(d,'box'));let cost=packs*val(d,'price');return res('Potrzebne wkręty',`${total} szt.`,[row('Opakowania',`${packs} szt.`),row('Zapas',`${fmt(val(d,'waste'),0)}%`),row('Koszt',val(d,'price')?money(cost):'nie podano')],'Dobierz długość i typ wkręta do materiału oraz środowiska pracy.',[`Wkręty: ${total} szt.`]);}},
 {id:'fugi',cat:'budowa',icon:'▦',name:'Kalkulator fug',tag:'płytki',desc:'Orientacyjne zużycie fugi do płytek.',formula:'kg/m² ≈ ((A+B)/(A×B)) × szer. fugi × gł. fugi × gęstość',fields:[field('area','Powierzchnia','m²',20),field('tileW','Szerokość płytki','mm',600),field('tileH','Długość płytki','mm',600),field('joint','Szerokość fugi','mm',3),field('depth','Głębokość fugi','mm',8),field('density','Gęstość orientacyjna','kg/l',1.6,true),field('price','Cena fugi za kg','zł/kg',0,true)],guide:'Zużycie fugi rośnie przy mniejszych płytkach i szerszych fugach.',example:'Duże płytki 60×60 cm zużyją dużo mniej fugi niż mozaika.',mistakes:'Nie licz samej powierzchni. Liczy się liczba i długość spoin.',calc:d=>{let kgm=((val(d,'tileW')+val(d,'tileH'))/(val(d,'tileW')*val(d,'tileH')))*val(d,'joint')*val(d,'depth')*val(d,'density');let kg=kgm*val(d,'area')*1.1;let cost=kg*val(d,'price');return res('Potrzebna fuga',`${fmt(kg,2)} kg`,[row('Zużycie',`${fmt(kgm,3)} kg/m²`),row('Zapas 10%',`uwzględniony`),row('Koszt',val(d,'price')?money(cost):'nie podano')],'Sprawdź zużycie na opakowaniu konkretnej fugi.',[`Fuga: ${fmt(kg,2)} kg`]);}},
 {id:'dylatacja',cat:'budowa',icon:'↔️',name:'Kalkulator dylatacji',tag:'posadzki',desc:'Sugerowany podział powierzchni na pola dylatacyjne.',formula:'liczba pól = ceil(długość / limit) × ceil(szerokość / limit)',fields:[field('length','Długość posadzki','m',8),field('width','Szerokość posadzki','m',5),field('limit','Maksymalny bok pola','m',4),field('joint','Szerokość dylatacji','mm',5,true)],guide:'Dylatacje ograniczają ryzyko spękań wynikających z pracy materiału.',example:'Pomieszczenie 8×5 m przy polu 4 m wymaga podziału na kilka pól.',mistakes:'Nie prowadź dylatacji przypadkowo. Powinna być skoordynowana z progami, słupami i okładziną.',calc:d=>{let nx=Math.ceil(val(d,'length')/val(d,'limit')),ny=Math.ceil(val(d,'width')/val(d,'limit'));let fields=nx*ny;return res('Liczba pól',`${fields} szt.`,[row('Podział wzdłuż',`${nx} części`),row('Podział wszerz',`${ny} części`),row('Orientacyjny wymiar pola',`${fmt(val(d,'length')/nx,2)} × ${fmt(val(d,'width')/ny,2)} m`)],'To podział orientacyjny. Układ dylatacji wymaga dopasowania do warstw i konstrukcji.',[`Pola dylatacyjne: ${fields} szt.`]);}},
 {id:'izolacja-poddasza',cat:'dach',icon:'🧣',name:'Kalkulator izolacji poddasza',tag:'ocieplenie',desc:'Ilość wełny lub izolacji na połacie.',formula:'powierzchnia = długość połaci × długość poddasza × liczba połaci × zapas',fields:[field('slopeL','Długość połaci','m',5),field('roofL','Długość dachu','m',8),field('sides','Liczba połaci','szt.',2),field('layers','Liczba warstw','szt.',2),field('pack','Powierzchnia paczki','m²',5.76,true),field('waste','Zapas','%',10),field('price','Cena paczki','zł',0,true)],guide:'Przy izolacji dwuwarstwowej licz powierzchnię dla każdej warstwy osobno.',example:'2 połacie po 5×8 m i 2 warstwy to 160 m² przed zapasem.',mistakes:'Nie zapomnij o docinkach, jętkach, koszach i mostkach termicznych.',calc:d=>{let area=val(d,'slopeL')*val(d,'roofL')*val(d,'sides')*val(d,'layers')*pct(val(d,'waste'));let packs=Math.ceil(area/val(d,'pack'));let cost=packs*val(d,'price');return res('Izolacja łącznie',`${fmt(area,1)} m²`,[row('Liczba paczek',`${packs} szt.`),row('Warstwy',`${fmt(val(d,'layers'),0)} szt.`),row('Koszt',val(d,'price')?money(cost):'nie podano')],'Sprawdź wymaganą grubość i lambdę izolacji dla konkretnej przegrody.',[`Izolacja: ${fmt(area,1)} m²`, `Paczki: ${packs} szt.`]);}},
 {id:'straty-materialu',cat:'budowa',icon:'％',name:'Kalkulator strat materiału',tag:'koszty',desc:'Dodaje zapas materiałowy do obliczonej ilości.',formula:'ilość z zapasem = ilość × (1 + strata/100)',fields:[field('qty','Ilość bazowa','',100),field('loss','Strata / zapas','%',10),field('price','Cena jednostkowa','zł',0,true)],guide:'Zapas zależy od materiału, docinek, jakości podłoża i doświadczenia wykonawcy.',example:'100 m² płytek + 10% = 110 m² zakupu.',mistakes:'Zapas 0% zwykle jest ryzykowny przy docinkach i uszkodzeniach.',calc:d=>{let total=val(d,'qty')*pct(val(d,'loss'));let extra=total-val(d,'qty');let cost=total*val(d,'price');return res('Ilość z zapasem',`${fmt(total,2)}`,[row('Dodatkowo',`${fmt(extra,2)}`),row('Zapas',`${fmt(val(d,'loss'),1)}%`),row('Koszt',val(d,'price')?money(cost):'nie podano')],'Dla płytek, drewna i izolacji zapas bywa różny — dopasuj go do realnego układu.',[`Materiał z zapasem: ${fmt(total,2)}`]);}},
 {id:'koszt-robocizny',cat:'koszty',icon:'👷',name:'Kalkulator kosztu robocizny',tag:'wycena',desc:'Koszt pracy według stawki godzinowej lub m².',formula:'koszt = ilość × stawka + koszty dodatkowe',fields:[select('mode','Sposób liczenia',[['hours','Godzinowo'],['area','Za m²'],['piece','Za sztukę']],'hours'),field('qty','Ilość / godziny','',40),field('rate','Stawka','zł',90),field('extra','Koszty dodatkowe','zł',300,true),field('margin','Marża / bufor','%',15,true)],guide:'Wycena powinna uwzględniać roboczogodziny, dojazd, zużycie narzędzi, podatki i bufor ryzyka.',example:'40 h × 90 zł + 300 zł + 15% = 4485 zł.',mistakes:'Nie licz tylko „gołej” stawki. Czas organizacyjny i poprawki też kosztują.',calc:d=>{let base=val(d,'qty')*val(d,'rate')+val(d,'extra');let total=base*pct(val(d,'margin'));return res('Koszt robocizny',money(total),[row('Koszt bazowy',money(base)),row('Bufor / marża',`${fmt(val(d,'margin'),1)}%`),row('Tryb',d.mode==='hours'?'godzinowo':d.mode==='area'?'za m²':'za sztukę')],'To kalkulacja ofertowa, nie zastępuje kosztorysu szczegółowego.',[`Robocizna: ${money(total)}`]);}},
 {id:'wynajem-narzedzia',cat:'koszty',icon:'🧰',name:'Kalkulator wynajmu narzędzia',tag:'koszty',desc:'Porównanie wynajmu dziennego z zakupem narzędzia.',formula:'koszt wynajmu = dni × stawka + kaucja/transport/zużycie',fields:[field('days','Liczba dni','dni',3),field('dayRate','Cena za dzień','zł',80),field('transport','Transport / odbiór','zł',50,true),field('consumables','Osprzęt i zużycie','zł',40,true),field('buy','Cena zakupu narzędzia','zł',650,true)],guide:'Wynajem opłaca się przy jednorazowych pracach, zakup przy częstym użyciu.',example:'3 dni × 80 zł + 90 zł kosztów = 330 zł.',mistakes:'Nie pomijaj transportu, osprzętu, kaucji i czasu odbioru.',calc:d=>{let rent=val(d,'days')*val(d,'dayRate')+val(d,'transport')+val(d,'consumables');let daysToBuy=val(d,'buy')/val(d,'dayRate');return res('Koszt wynajmu',money(rent),[row('Cena zakupu',val(d,'buy')?money(val(d,'buy')):'nie podano'),row('Próg zakupu',val(d,'buy')?`${fmt(daysToBuy,1)} dni najmu`:'nie podano'),row('Różnica vs zakup',val(d,'buy')?money(val(d,'buy')-rent):'nie podano')],val(d,'buy')&&rent>val(d,'buy')?'Zakup może być korzystniejszy niż wynajem.':'Wynajem wygląda sensownie przy krótkiej pracy.',[`Wynajem narzędzia: ${money(rent)}`]);}},
 {id:'powierzchnia-scian',cat:'budowa',icon:'▭',name:'Kalkulator powierzchni ścian',tag:'wykończenie',desc:'Metraż ścian pomieszczenia z odjęciem okien i drzwi.',formula:'A = 2 × (długość + szerokość) × wysokość − otwory',fields:[field('length','Długość pomieszczenia','m',5),field('width','Szerokość pomieszczenia','m',4),field('height','Wysokość','m',2.6),field('openings','Okna i drzwi','m²',4),field('price','Cena za m²','zł/m²',0,true)],guide:'Metraż ścian przydaje się do farby, gładzi, tynku, tapety i paneli.',example:'Pokój 5×4×2,6 m ma 46,8 m² ścian brutto.',mistakes:'Nie odejmuj małych otworów, jeśli wykonawca liczy je jako obrabiane powierzchnie.',calc:d=>{let gross=2*(val(d,'length')+val(d,'width'))*val(d,'height');let net=Math.max(0,gross-val(d,'openings'));let cost=net*val(d,'price');return res('Powierzchnia ścian netto',`${fmt(net,2)} m²`,[row('Powierzchnia brutto',`${fmt(gross,2)} m²`),row('Otwory',`${fmt(val(d,'openings'),2)} m²`),row('Koszt',val(d,'price')?money(cost):'nie podano')],'Sposób liczenia otworów zależy od zakresu prac i ustaleń z wykonawcą.',[`Ściany: ${fmt(net,2)} m²`]);}},
 {id:'wentylacja-pomieszczenia',cat:'instalacje',icon:'💨',name:'Kalkulator wentylacji pomieszczenia',tag:'wentylacja',desc:'Kubatura i wymagana wymiana powietrza ACH.',formula:'wydajność = kubatura × wymiany/h',fields:[field('length','Długość','m',5),field('width','Szerokość','m',4),field('height','Wysokość','m',2.6),field('ach','Wymiany powietrza','1/h',1.5),field('fan','Wydajność jednego wentylatora','m³/h',120,true)],guide:'ACH to liczba wymian powietrza na godzinę. Wymagania zależą od funkcji pomieszczenia.',example:'Pokój 52 m³ przy 1,5 wymiany/h wymaga ok. 78 m³/h.',mistakes:'Nie traktuj wyniku jako projektu wentylacji. Liczą się nawiew, wywiew, opory i hałas.',calc:d=>{let vol=val(d,'length')*val(d,'width')*val(d,'height');let flow=vol*val(d,'ach');let fans=Math.ceil(flow/val(d,'fan'));return res('Wymagana wydajność',`${fmt(flow,0)} m³/h`,[row('Kubatura',`${fmt(vol,1)} m³`),row('Wymiany/h',`${fmt(val(d,'ach'),1)}`),row('Liczba wentylatorów',val(d,'fan')?`${fans} szt.`:'nie podano')],'Dobór wentylacji wymaga sprawdzenia przepisów, oporów instalacji i bilansu nawiewu.',[`Wentylacja: ${fmt(flow,0)} m³/h`]);}},
 {id:'deski-tarasowe',cat:'drewno',icon:'▥',name:'Kalkulator desek tarasowych',tag:'taras',desc:'Liczba desek i metry bieżące na taras.',formula:'rzędy = szerokość / (deska + szczelina)',fields:[field('deckW','Szerokość tarasu w poprzek desek','m',4),field('deckL','Długość tarasu wzdłuż desek','m',5),field('boardW','Szerokość deski','mm',145),field('gap','Szczelina','mm',6),field('stockL','Długość handlowa deski','m',3),field('waste','Zapas','%',8),field('price','Cena deski','zł/szt.',0,true)],guide:'Ułóż deski tak, aby łączenia wypadały na legarach i nie tworzyły jednej linii.',example:'Taras 4 m szerokości przy desce 145 mm i szczelinie 6 mm wymaga ok. 27 rzędów.',mistakes:'Nie zapominaj o szczelinach dylatacyjnych przy ścianie i między deskami.',calc:d=>{let rows=Math.ceil(val(d,'deckW')/((val(d,'boardW')+val(d,'gap'))/1000));let per=Math.ceil(val(d,'deckL')/val(d,'stockL'));let pcs=Math.ceil(rows*per*pct(val(d,'waste')));let cost=pcs*val(d,'price');return res('Deski handlowe',`${pcs} szt.`,[row('Rzędy desek',`${rows}`),row('Elementy na rząd',`${per}`),row('Metry bieżące',`${fmt(pcs*val(d,'stockL'),1)} mb`),row('Koszt',val(d,'price')?money(cost):'nie podano')],'Kalkulator nie optymalizuje przesunięcia łączeń i długości docinek.',[`Deski tarasowe: ${pcs} szt.`]);}},
 {id:'legary',cat:'drewno',icon:'▤',name:'Kalkulator legarów',tag:'taras',desc:'Liczba legarów i metry bieżące pod taras.',formula:'liczba legarów = szerokość / rozstaw + 1',fields:[field('deckW','Szerokość tarasu','m',4),field('deckL','Długość legara','m',5),field('spacing','Rozstaw legarów','cm',45),field('stockL','Długość handlowa legara','m',4),field('waste','Zapas','%',8),field('price','Cena legara','zł/szt.',0,true)],guide:'Rozstaw legarów zależy od grubości deski i zaleceń producenta systemu tarasowego.',example:'Taras 4 m przy rozstawie 45 cm wymaga ok. 10 linii legarów.',mistakes:'Za duży rozstaw legarów powoduje uginanie i pracę desek.',calc:d=>{let lines=Math.ceil(val(d,'deckW')/(val(d,'spacing')/100))+1;let pcs=Math.ceil(lines*Math.ceil(val(d,'deckL')/val(d,'stockL'))*pct(val(d,'waste')));let mb=pcs*val(d,'stockL');let cost=pcs*val(d,'price');return res('Legary',`${pcs} szt.`,[row('Linie legarów',`${lines}`),row('Metry bieżące',`${fmt(mb,1)} mb`),row('Koszt',val(d,'price')?money(cost):'nie podano')],'Sprawdź zalecany rozstaw dla konkretnej deski tarasowej.',[`Legary: ${pcs} szt.`]);}},
 {id:'przekatna-345',cat:'budowa',icon:'📐',name:'Kalkulator przekątnej 3-4-5',tag:'kontrola',desc:'Przekątna prostokąta i kontrola kąta prostego.',formula:'d = √(a² + b²)',fields:[field('a','Bok A','m',4),field('b','Bok B','m',3),field('measured','Zmierzona przekątna','m',5,true)],guide:'Metoda 3-4-5 to praktyczna kontrola kąta prostego przy trasowaniu.',example:'Boki 3 m i 4 m powinny mieć przekątną 5 m.',mistakes:'Mierz po tych samych punktach odniesienia. Błąd kilku mm rośnie przy dużych wymiarach.',calc:d=>{let diag=Math.sqrt(val(d,'a')**2+val(d,'b')**2);let diff=val(d,'measured')?val(d,'measured')-diag:0;return res('Prawidłowa przekątna',`${fmt(diag,3)} m`,[row('Bok A',`${fmt(val(d,'a'),3)} m`),row('Bok B',`${fmt(val(d,'b'),3)} m`),row('Różnica pomiaru',val(d,'measured')?`${fmt(diff*1000,0)} mm`:'nie podano')],Math.abs(diff)>0.01&&val(d,'measured')?'Kąt może wymagać korekty.':'Dla kontroli wpisz zmierzoną przekątną.',[`Przekątna: ${fmt(diag,3)} m`]);}}
];
const store={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch(e){return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let state={mode:'simple',current:calcs[0].id,search:'',lastResult:null};
function cat(id){return cats.find(c=>c.id===id)||cats[0]} function calc(id){return calcs.find(c=>c.id===id)||calcs[0]}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function route(){const h=location.hash||'#/'; if(h.startsWith('#/kategoria/')) renderCategory(h.split('/')[2]); else if(h.startsWith('#/kalkulator/')) renderCalc(h.split('/')[2]); else if(h==='#/kategorie') renderCategoriesPage(); else if(h==='#/ulubione') renderFavs(); else if(h==='#/historia') renderHistory(); else if(h==='#/lista') renderShopping(); else if(h==='#/kontakt') renderContact(); else renderHome(); renderNav();}
function renderNav(){const links=[['#/','Start'],['#/kategorie','Kategorie'],['#/historia','Historia'],['#/lista','Lista zakupów'],['#/kontakt','Kontakt']]; $('#mainNav').innerHTML=links.map(([u,t])=>`<a class="nav-link ${(location.hash||'#/')===u?'active':''}" href="${u}">${t}</a>`).join(''); $('#footerCats').innerHTML=cats.map(c=>`<a href="#/kategoria/${c.id}">${c.icon} ${c.name}</a>`).join('');}
function searchBlock(){return `<div class="search-wrap"><span>${iconsSearch()}</span><input id="globalSearch" class="search-input" value="${state.search}" placeholder="Szukaj: schody, krokwie, fuga, taras, robocizna..."/><button class="search-clear" id="clearSearch" type="button">×</button></div>`}
function iconsSearch(){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-4-4"></path></svg>'}
function bindSearch(){const inp=$('#globalSearch'); if(!inp)return; inp.addEventListener('input',e=>{state.search=e.target.value; renderSearchResults()}); $('#clearSearch')?.addEventListener('click',()=>{state.search=''; inp.value=''; renderSearchResults()});}
function filtered(){let q=state.search.toLowerCase().trim();return !q?calcs:calcs.filter(c=>(c.name+' '+c.desc+' '+c.tag+' '+cat(c.cat).name).toLowerCase().includes(q))}
function renderHome(){let popular=['schody','spadek-kanalizacji','spadek-tarasu','dlugosc-krokwi','fugi','deski-tarasowe']; $('#app').innerHTML=`<section class="hero"><div class="hero-inner"><div><span class="eyebrow">Kalkulatory budowlane Home Lab&Fix</span><h1>Policz materiały, spadki i koszty <em>zanim kupisz za dużo.</em></h1><p>Beton, schody, dach, krokwie, taras, fuga, dylatacje, robocizna i instalacje — praktyczne narzędzia do szybkich obliczeń na budowie i w domu.</p>${searchBlock()}</div><div class="hero-sketch"><div class="sketch-card"><div class="sketch-top"><span>PROJEKT</span><b>HL&F</b></div><div class="sketch-grid"><div class="sketch-item"><small>Kalkulatory</small><strong>${calcs.length}</strong></div><div class="sketch-item"><small>Kategorie</small><strong>${cats.length}</strong></div><div class="sketch-item"><small>Historia</small><strong>✓</strong></div><div class="sketch-item"><small>Lista zakupów</small><strong>✓</strong></div></div><div class="sketch-line"></div></div></div></div></section><section class="section compact"><div class="section-head"><div><h2>Najczęściej używane</h2><p>Szybki pasek pod publikacje z Facebooka i najczęstsze pytania odbiorców.</p></div></div><div class="quick-strip">${popular.map(id=>`<a class="quick-chip" href="#/kalkulator/${id}">${calc(id).icon} ${calc(id).name}</a>`).join('')}</div><div id="searchResults"></div></section><section class="section"><div class="section-head"><div><h2>Kategorie kalkulatorów</h2><p>Każda kategoria ma własny widok, opis i listę narzędzi.</p></div><a class="link-arrow" href="#/kategorie">Pokaż wszystkie →</a></div>${categoryGrid()}</section><section class="section"><div class="question-box"><div><h2>Zadaj pytanie do obliczenia</h2><p>Brakuje kalkulatora? Napisz, co chcesz policzyć. Dane zostaną zapisane lokalnie jako zgłoszenie do rozwinięcia strony.</p>${questionForm()}</div><div class="fb-box"><h3>Napisz do nas na Facebooku</h3><p>Możesz też wysłać wiadomość bezpośrednio na stronę Home Lab&Fix.</p><a class="btn" href="https://facebook.com/homelabfix" target="_blank" rel="noreferrer">Otwórz Facebook Home Lab&Fix</a></div></div></section>`; bindSearch(); bindQuestion(); renderSearchResults();}
function categoryGrid(){return `<div class="category-grid">${cats.map(c=>`<a class="category-card" style="--card-tint:${c.tint}" href="#/kategoria/${c.id}"><span class="icon-box">${c.icon}</span><h3>${c.name}</h3><p>${c.desc}</p><span class="count">${calcs.filter(x=>x.cat===c.id).length} kalkulatorów</span></a>`).join('')}</div>`}
function renderCategoriesPage(){ $('#app').innerHTML=`<section class="section"><div class="section-head"><div><span class="eyebrow">Kategorie</span><h2>Wybierz dział obliczeń</h2><p>Budowa, dach, drewno, instalacje i koszty z osobnymi adresami URL.</p></div></div>${categoryGrid()}</section>`;}
function renderCategory(id){let c=cat(id), list=calcs.filter(x=>x.cat===c.id); $('#app').innerHTML=`<section class="section"><div class="section-head"><div><span class="eyebrow">${c.icon} ${c.name}</span><h2>${c.name}</h2><p>${c.desc}</p></div><a class="link-arrow" href="#/kategorie">Kategorie →</a></div><div class="cards-grid">${list.map(toolCard).join('')}</div></section>`;}
function toolCard(c){return `<a class="small-card" href="#/kalkulator/${c.id}"><h3>${c.icon} ${c.name}</h3><p>${c.desc}</p><b class="link-arrow">Otwórz kalkulator →</b></a>`}
function renderSearchResults(){let box=$('#searchResults'); if(!box)return; if(!state.search.trim()){box.innerHTML='';return} let list=filtered(); box.innerHTML=`<div class="section-head" style="margin-top:28px"><div><h2>Wyniki wyszukiwania</h2><p>Znaleziono: ${list.length}</p></div></div><div class="cards-grid">${list.map(toolCard).join('')}</div>`;}
function renderCalc(id){let c=calc(id), ca=cat(c.cat); state.current=c.id; let fields=c.fields.filter(f=>state.mode==='advanced'||!f.advanced); $('#app').innerHTML=`<section class="section"><div class="tools-layout"><aside class="tools-sidebar"><strong>Kalkulatory w kategorii</strong><div class="tools-list" style="margin-top:12px">${calcs.filter(x=>x.cat===c.cat).map(x=>`<a class="tool-row ${x.id===c.id?'active':''}" href="#/kalkulator/${x.id}"><strong>${x.icon} ${x.name}</strong><small>${x.desc}</small></a>`).join('')}</div></aside><article class="calc-panel"><div class="calc-head"><div><div class="tag-row"><span class="tag">${ca.icon} ${ca.name}</span><span class="tag">${c.tag}</span><button class="tag" id="favBtn" type="button">${isFav(c.id)?'★ Ulubiony':'☆ Dodaj do ulubionych'}</button></div><h1 class="calc-title">${c.name}</h1><p class="calc-desc">${c.desc}</p></div><div class="calc-icon">${c.icon}</div></div><div class="project-field"><label for="projectName">Nazwa projektu / zlecenia / inwestycji</label><input id="projectName" placeholder="np. Taras u klienta — Warszawa" value="${store.get('lastProject','')}"></div><div class="mode-row"><div class="segmented"><button id="simpleMode" class="${state.mode==='simple'?'active':''}" type="button">Tryb prosty</button><button id="advancedMode" class="${state.mode==='advanced'?'active':''}" type="button">Tryb zaawansowany</button></div><button class="link-button" id="compareBtn" type="button">Porównaj warianty A/B</button></div><div class="formula-card"><strong>Wzór</strong><code>${c.formula}</code></div><div class="fields-grid">${fields.map(renderField).join('')}</div><div id="resultBox"></div><div class="action-row"><button class="primary" id="copyResult">Kopiuj wynik</button><button id="copyReport">Kopiuj raport</button><button class="green" id="addShopping">Dodaj do listy zakupów</button><button id="shareCalc">Udostępnij</button><button id="saveCheat">Zapisz jako ściągę</button></div><div id="compareDrawer" class="drawer"></div><div class="help-card"><h3>Jak działa ten kalkulator?</h3><p>${c.guide}</p><h3>Przykład</h3><p>${c.example}</p><h3>Na co uważać?</h3><p>${c.mistakes}</p></div></article></div></section>`; bindCalc(c); calcNow();}
function renderField(f){ if(f.type==='select')return `<div class="field"><label>${f.label}</label><select id="f_${f.id}">${f.options.map(o=>`<option value="${o[0]}" ${o[0]===f.value?'selected':''}>${o[1]}</option>`).join('')}</select></div>`; return `<div class="field"><label for="f_${f.id}">${f.label}<small>${f.unit||''}</small></label><input id="f_${f.id}" type="number" step="any" value="${f.value}" placeholder="${f.hint||''}"></div>`}
function dataFor(c,prefix='f_'){let d={}; c.fields.forEach(f=>{let el=$('#'+prefix+f.id); d[f.id]=el? (f.type==='select'?el.value:val({x:el.value},'x')) : f.value}); return d;}
function calcNow(){let c=calc(state.current), d=dataFor(c), r=c.calc(d); state.lastResult={calcId:c.id,calcName:c.name,project:$('#projectName')?.value.trim()||'Bez nazwy projektu',date:new Date().toLocaleString('pl-PL'),data:d,result:r}; $('#resultBox').innerHTML=`<div class="result-card"><div class="result-main"><span>${r.label}</span><strong>${r.value}</strong></div><div class="result-details">${r.rows.map(x=>`<div><small>${x.label}</small><b>${x.value}</b></div>`).join('')}</div>${r.warning?`<div class="result-warning">${r.warning}</div>`:''}</div>`; store.set('lastProject',$('#projectName')?.value||'');}
function bindCalc(c){c.fields.forEach(f=>$('#f_'+f.id)?.addEventListener('input',calcNow)); $('#projectName').addEventListener('input',calcNow); $('#favBtn').onclick=()=>toggleFav(c.id); $('#simpleMode').onclick=()=>{state.mode='simple';renderCalc(c.id)}; $('#advancedMode').onclick=()=>{state.mode='advanced';renderCalc(c.id)}; $('#copyResult').onclick=()=>copy(resultText()); $('#copyReport').onclick=()=>{addHistory();copy(reportText());}; $('#addShopping').onclick=()=>addShopping(); $('#shareCalc').onclick=()=>shareCalc(); $('#saveCheat').onclick=()=>copy(cheatText()); $('#compareBtn').onclick=()=>renderCompare(c);}
function resultText(){let r=state.lastResult;return `${r.project}\n${r.calcName}: ${r.result.label} — ${r.result.value}`}
function reportText(){let r=state.lastResult;return `Raport obliczenia — Home Lab&Fix\nProjekt: ${r.project}\nKalkulator: ${r.calcName}\nData: ${r.date}\nWynik: ${r.result.label} — ${r.result.value}\n${r.result.rows.map(x=>`${x.label}: ${x.value}`).join('\n')}\nUwaga: wynik orientacyjny.`}
function cheatText(){let c=calc(state.current);return `Ściąga Home Lab&Fix\n${c.name}\nWzór: ${c.formula}\nPrzykład: ${c.example}\nNa co uważać: ${c.mistakes}`}
async function copy(t){try{await navigator.clipboard.writeText(t);toast('Skopiowano')}catch(e){prompt('Skopiuj ręcznie:',t)}}
function addHistory(){let h=store.get('history',[]); h.unshift(state.lastResult); store.set('history',h.slice(0,60)); toast('Dodano do historii')}
function addShopping(){let r=state.lastResult; let items=store.get('shopping',[]); (r.result.shopping?.length?r.result.shopping:[`${r.calcName}: ${r.result.value}`]).forEach(x=>items.unshift({project:r.project,text:x,date:r.date})); store.set('shopping',items.slice(0,120)); toast('Dodano do listy zakupów')}
async function shareCalc(){let c=calc(state.current), url=location.origin+location.pathname+`#/kalkulator/${c.id}`, text=resultText(); if(navigator.share){try{await navigator.share({title:c.name,text,url});return}catch(e){}} copy(`${text}\n${url}`)}
function isFav(id){return store.get('favs',[]).includes(id)} function toggleFav(id){let f=store.get('favs',[]); f=f.includes(id)?f.filter(x=>x!==id):[id,...f]; store.set('favs',f); toast(f.includes(id)?'Dodano do ulubionych':'Usunięto z ulubionych'); renderCalc(id)}
function renderCompare(c){let dr=$('#compareDrawer'); dr.classList.toggle('open'); if(!dr.classList.contains('open'))return; const fields=c.fields.filter(f=>!f.advanced).map(f=>`<div class="field"><label>${f.label}<small>${f.unit||''}</small></label><input type="number" step="any" id="A_${f.id}" value="${f.value}"><input style="margin-top:7px" type="number" step="any" id="B_${f.id}" value="${f.value}"></div>`).join(''); dr.innerHTML=`<div class="help-card"><h3>Porównanie wariantów A/B</h3><p>Pierwsze pole to wariant A, drugie pole to wariant B.</p><div class="fields-grid">${fields}</div><div class="action-row"><button class="primary" id="runCompare">Porównaj</button></div><div id="compareResult"></div></div>`; $('#runCompare').onclick=()=>{let da=dataFor(c,'A_'),db=dataFor(c,'B_'),ra=c.calc(da),rb=c.calc(db); $('#compareResult').innerHTML=`<div class="compare-grid"><div class="compare-box"><h3>Wariant A</h3><strong>${ra.label}: ${ra.value}</strong></div><div class="compare-box"><h3>Wariant B</h3><strong>${rb.label}: ${rb.value}</strong></div></div>`};}
function renderHistory(){let h=store.get('history',[]); $('#app').innerHTML=`<section class="section"><div class="section-head"><div><span class="eyebrow">Historia</span><h2>Historia obliczeń</h2><p>Wyniki zapisują nazwę projektu/zlecenia/inwestycji, żeby łatwo rozdzielić kilka prac.</p></div><button class="btn" id="clearH">Wyczyść</button></div>${h.length?h.map((x,i)=>`<div class="history-item"><strong>${x.project}</strong><div>${x.calcName}: <b>${x.result.label} — ${x.result.value}</b></div><div class="history-meta"><span>${x.date}</span><a href="#/kalkulator/${x.calcId}">otwórz kalkulator</a></div></div>`).join(''):'<div class="empty">Brak zapisanych obliczeń. Użyj przycisku „Kopiuj raport” przy kalkulatorze.</div>'}</section>`; $('#clearH')?.addEventListener('click',()=>{store.set('history',[]);route()});}
function renderShopping(){let s=store.get('shopping',[]); $('#app').innerHTML=`<section class="section"><div class="section-head"><div><span class="eyebrow">Lista zakupów</span><h2>Lista zakupów z kalkulatorów</h2><p>Dodawaj materiały z wyników i kopiuj całość do wiadomości lub notatnika.</p></div><div class="action-row"><button id="copyShop" class="primary">Kopiuj listę</button><button id="clearShop">Wyczyść</button></div></div>${s.length?s.map(x=>`<div class="shopping-item"><b>${x.text}</b><small>${x.project} • ${x.date}</small></div>`).join(''):'<div class="empty">Lista zakupów jest pusta.</div>'}</section>`; $('#copyShop')?.addEventListener('click',()=>copy(s.map(x=>`${x.project}: ${x.text}`).join('\n'))); $('#clearShop')?.addEventListener('click',()=>{store.set('shopping',[]);route()});}
function renderFavs(){let f=store.get('favs',[]).map(calc); $('#app').innerHTML=`<section class="section"><div class="section-head"><div><span class="eyebrow">Ulubione</span><h2>Ulubione kalkulatory</h2><p>Zapisywane lokalnie w telefonie użytkownika.</p></div></div>${f.length?`<div class="cards-grid">${f.map(toolCard).join('')}</div>`:'<div class="empty">Brak ulubionych kalkulatorów.</div>'}</section>`;}
function questionForm(){return `<form id="questionForm" class="two-col"><div class="field"><label>Temat kalkulatora</label><input name="topic" placeholder="np. kalkulator pergoli 4 × 3 m"></div><div class="field"><label>Opis problemu</label><textarea name="msg" placeholder="Co użytkownik powinien wpisać i jaki wynik dostać?"></textarea></div><button class="btn primary" type="submit">Zapisz zgłoszenie</button></form>`}
function renderContact(){ $('#app').innerHTML=`<section class="section"><div class="question-box"><div><span class="eyebrow">Kontakt</span><h2>Zadaj pytanie do obliczenia</h2><p>Dodaj pomysł na nowy kalkulator albo pytanie techniczne do opracowania.</p>${questionForm()}</div><div class="fb-box"><h3>Napisz do nas na Facebooku</h3><p>Najprostsza opcja kontaktu z Home Lab&Fix.</p><a class="btn" href="https://facebook.com/homelabfix" target="_blank" rel="noreferrer">Otwórz Facebook</a></div></div></section>`; bindQuestion();}
function bindQuestion(){let f=$('#questionForm'); if(!f)return; f.onsubmit=e=>{e.preventDefault(); let q=store.get('questions',[]); q.unshift({topic:f.topic.value,msg:f.msg.value,date:new Date().toLocaleString('pl-PL')}); store.set('questions',q); f.reset(); toast('Zgłoszenie zapisane lokalnie');}}
function boot(){document.documentElement.dataset.theme=store.get('theme','light'); $('#themeToggle').textContent=document.documentElement.dataset.theme==='dark'?'☀️':'🌙'; $('#themeToggle').onclick=()=>{let t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;store.set('theme',t);$('#themeToggle').textContent=t==='dark'?'☀️':'🌙'}; $('#menuToggle').onclick=()=>$('#mainNav').classList.toggle('open'); $('#mobileSearch').onclick=()=>{location.hash='#/';setTimeout(()=>$('#globalSearch')?.focus(),80)}; window.addEventListener('hashchange',route); route();}
boot();
